"""SPEC-grag implementation package."""

from spec_grag.manifest import (
    ManifestReconciliation,
    ManifestUpdateStatus,
    SourceManifest,
    SourceManifestEntry,
    build_current_section_manifest,
    load_source_manifest,
    next_source_manifest,
    reconcile_manifests,
    write_source_manifest_atomic,
)
from spec_grag.extraction import (
    ExtractionProvenance,
    KG_VALIDATION_SCHEMA,
    SPEC_GRAG_EXTRACT_PROMPT,
    make_schema_llm_path_extractor,
)
from spec_grag.graph_ops import safe_delete_by_section
from spec_grag.llm_adapters import CLIAdapterError, CodexCLIAdapter
from spec_grag.protocol import (
    AgentCapabilities,
    AgenticSearchCandidate,
    Command,
    ConversationContext,
    ConversationMessage,
    CoreResult,
    ErrorResult,
    ExecutionMetadata,
    FreshnessReport,
    InjectionContext,
    NeedMoreContextResult,
    RealignResult,
    RequestOptions,
    ResultEnvelope,
    ResultStatus,
    ResultType,
    SlashCommandRequest,
)

__all__ = [
    "AgentCapabilities",
    "AgenticSearchCandidate",
    "Command",
    "ConversationContext",
    "ConversationMessage",
    "CoreResult",
    "ErrorResult",
    "ExecutionMetadata",
    "ExtractionProvenance",
    "FreshnessReport",
    "InjectionContext",
    "KG_VALIDATION_SCHEMA",
    "ManifestReconciliation",
    "ManifestUpdateStatus",
    "NeedMoreContextResult",
    "RealignResult",
    "RequestOptions",
    "ResultEnvelope",
    "ResultStatus",
    "ResultType",
    "SlashCommandRequest",
    "SourceManifest",
    "SourceManifestEntry",
    "SPEC_GRAG_EXTRACT_PROMPT",
    "build_current_section_manifest",
    "CLIAdapterError",
    "CodexCLIAdapter",
    "load_source_manifest",
    "make_schema_llm_path_extractor",
    "next_source_manifest",
    "reconcile_manifests",
    "safe_delete_by_section",
    "write_source_manifest_atomic",
]
