"""LLM-generated Chapter Key Anchor.

Chapter Key Anchor is generated by an LLM per chapter. This module runs
a per-chapter LLM call that emits `summary`, `key_topics`,
`important_sections`, and `notes` shaped for Agentic Search entry.

The module mirrors `spec_grag/section_metadata.py`:
* `CHAPTER_ANCHORS_PROMPT_VERSION` namespaces the cache so a prompt
  bump invalidates prior outputs.
* `ChapterAnchorsCache` reads / writes per-chapter cache files at
  `<cache_dir>/chapter_anchors/<hash>.json` where `cache_dir` is the
  `.spec-grag/cache/` directory passed in by `core.py`.
* `generate_chapter_anchors` is the main entry point. It accepts the
  same building blocks `core.py` already has (sections, section
  metadata, optional Core Concept text) and an LLM provider, runs one
  LLM call per chapter, and marks chapters failed when the provider
  fails or returns an unparseable response.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from spec_grag.llm_provider import (
    DEFAULT_METADATA_VERSION,
    FakeLlmProvider,
    LlmGenerationResult,
    LlmProvider,
    LlmRequest,
    build_spec_core_llm_provider,
    generate_with_retries,
    select_llm_provider_config,
)


CHAPTER_ANCHORS_PROMPT_VERSION = "chapter-anchors-v1"
CHAPTER_ANCHORS_ROLE = "agentic_search_entry_not_evidence"


@dataclass(frozen=True)
class ChapterAnchorsGeneration:
    artifact: dict[str, Any]
    chapters: list[dict[str, Any]]
    llm_results: list[LlmGenerationResult]
    llm_calls: int
    cache_hits: int
    failed_chapter_ids: list[str]


class ChapterAnchorsCache:
    """File cache for the per-chapter LLM output.

    Cache key is scoped to chapter_id, the sorted list of section
    source_hashes in the chapter, prompt_version, model, provider,
    metadata_version, and whether Core Concept text is included. An
    unchanged chapter reuses its anchor even when other chapters change.
    """

    def __init__(self, cache_dir: str | Path) -> None:
        self.cache_dir = Path(cache_dir)

    def key_for(
        self,
        chapter_id: str,
        section_hashes: Sequence[str],
        *,
        prompt_version: str = CHAPTER_ANCHORS_PROMPT_VERSION,
        model: str = "fake",
        provider_id: str = "fake",
        metadata_version: int = DEFAULT_METADATA_VERSION,
        concept_hash: str = "",
    ) -> str:
        payload = {
            "chapter_id": chapter_id,
            "section_hashes": sorted(str(value) for value in section_hashes),
            "prompt_version": prompt_version,
            "model": model,
            "provider": provider_id,
            "metadata_version": metadata_version,
            "concept_hash": concept_hash,
        }
        return _sha256_text(_stable_json(payload))

    def load(self, cache_key: str) -> dict[str, Any] | None:
        path = self.path_for_key(cache_key)
        if not path.is_file():
            return None
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        if not isinstance(payload, Mapping):
            return None
        entry = payload.get("anchor")
        if not isinstance(entry, Mapping):
            return None
        return dict(entry)

    def store(self, anchor: Mapping[str, Any], cache_key: str) -> Path:
        path = self.path_for_key(cache_key)
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "cache_key": cache_key,
            "artifact_role": CHAPTER_ANCHORS_ROLE,
            "anchor": dict(anchor),
        }
        path.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return path

    def path_for_key(self, cache_key: str) -> Path:
        return self.cache_dir / "chapter_anchors" / f"{cache_key}.json"


def generate_chapter_anchors(
    sections: Sequence[Mapping[str, Any]],
    section_metadata_entries: Sequence[Mapping[str, Any]],
    *,
    config: Any | None = None,
    llm_config: Any | None = None,
    provider: LlmProvider | None = None,
    cache_dir: str | Path | None = None,
    concept_text: str | None = None,
    generated_at: str | None = None,
    prompt_version: str = CHAPTER_ANCHORS_PROMPT_VERSION,
    rebuild_all: bool = False,
) -> ChapterAnchorsGeneration:
    """Run one LLM call per chapter and assemble the chapter_anchors artifact.

    When LLM generation fails or returns an unparseable response, the
    affected chapter is skipped and the artifact status is marked
    `failed`. No alternate chapter anchor is generated for failed
    chapters.

    `rebuild_all=True` honors the `--all` / `--rebuild` CLI contract:
    the on-disk chapter anchor cache is bypassed for the load step
    (every chapter is recomputed via LLM). New entries are still
    written to the cache so subsequent default-mode runs can reuse
    them. When `rebuild_all=False` (default), unchanged chapters
    (`section_hashes` + `concept_hash` + `prompt_version` + `model` +
    `provider` unchanged) reuse the cached anchor.
    """

    metadata_by_section_id = {
        str(entry.get("section_id") or entry.get("source_section_id") or ""): dict(entry)
        for entry in section_metadata_entries
        if isinstance(entry, Mapping)
    }
    metadata_by_section_id.pop("", None)

    chapters = _group_sections_by_chapter(sections)
    if not chapters:
        return ChapterAnchorsGeneration(
            artifact={
                "status": "success",
                "chapters": [],
                "generated_at": generated_at,
            },
            chapters=[],
            llm_results=[],
            llm_calls=0,
            cache_hits=0,
            failed_chapter_ids=[],
        )

    selected_llm_config = _select_llm_config(
        llm_config if llm_config is not None else _config_value(config, "llm", None)
    )
    provider = _resolve_provider(provider, selected_llm_config)
    provider_id = str(getattr(provider, "provider_id", provider.__class__.__name__))
    model = _model_name(selected_llm_config, provider_id)
    effort = _config_value(selected_llm_config, "effort", None)
    timeout_sec = int(_config_value(selected_llm_config, "timeout_sec", 120))
    max_retries = int(_config_value(selected_llm_config, "max_retries", 1))
    metadata_version = int(_config_value(selected_llm_config, "metadata_version", DEFAULT_METADATA_VERSION))
    concept_hash = _sha256_text(concept_text or "")
    cache = ChapterAnchorsCache(cache_dir) if cache_dir is not None else None

    llm_results: list[LlmGenerationResult] = []
    failed_chapter_ids: list[str] = []
    failure_reasons_by_chapter: dict[str, str] = {}
    cache_hits = 0
    output_chapters: list[dict[str, Any]] = []

    for chapter in chapters:
        chapter_id = chapter["chapter_id"]
        section_ids = chapter["source_section_ids"]
        section_hashes = [
            metadata_by_section_id.get(section_id, {}).get("source_hash") or ""
            for section_id in section_ids
        ]
        cache_key = ""
        if cache is not None:
            cache_key = cache.key_for(
                chapter_id,
                section_hashes,
                prompt_version=prompt_version,
                model=model,
                provider_id=provider_id,
                metadata_version=metadata_version,
                concept_hash=concept_hash,
            )
            cached = None if rebuild_all else cache.load(cache_key)
            if cached is not None:
                cached.setdefault("source_section_ids", list(section_ids))
                cached.setdefault("chapter_id", chapter_id)
                cached["generated_at"] = generated_at
                output_chapters.append(cached)
                cache_hits += 1
                continue

        request = _build_chapter_request(
            chapter,
            metadata_by_section_id,
            section_hashes=section_hashes,
            concept_text=concept_text,
            prompt_version=prompt_version,
            model=model,
            effort=effort,
            metadata_version=metadata_version,
        )
        result = generate_with_retries(
            provider,
            request,
            required_fields=("summary", "key_topics", "important_sections", "notes"),
            field_schema={
                "summary": object,
                "key_topics": "list[string]",
                "important_sections": "list[string]",
                "notes": "list[string]",
            },
            timeout_sec=timeout_sec,
            max_retries=max_retries,
        )
        llm_results.append(result)
        output_value = result.artifact.output if result.artifact is not None else {}
        anchor = _anchor_from_llm_output(
            chapter,
            metadata_by_section_id,
            llm_output=output_value if result.status == "success" else None,
            generated_at=generated_at,
        )
        if anchor is None:
            failed_chapter_ids.append(chapter_id)
            if result.status != "success":
                error_message = _llm_error_message(result)
                failure_reasons_by_chapter[chapter_id] = (
                    f"llm_generation_{result.status}: {error_message or 'no detail'}"
                )
            else:
                failure_reasons_by_chapter[chapter_id] = (
                    "llm_output_unparseable_or_missing_summary"
                )
            continue
        if cache is not None and cache_key:
            cache.store(anchor, cache_key)
        output_chapters.append(anchor)

    artifact = {
        "status": "failed" if failed_chapter_ids else "success",
        "chapters": output_chapters,
        "generated_at": generated_at,
        "generation": {
            "stage": "chapter_anchors",
            "prompt_version": prompt_version,
            "model": model,
            "provider": provider_id,
            "metadata_version": metadata_version,
            "failed_chapter_ids": failed_chapter_ids,
            "failure_reasons_by_chapter": failure_reasons_by_chapter,
        },
    }
    return ChapterAnchorsGeneration(
        artifact=artifact,
        chapters=output_chapters,
        llm_results=llm_results,
        llm_calls=len(llm_results),
        cache_hits=cache_hits,
        failed_chapter_ids=failed_chapter_ids,
    )


def _group_sections_by_chapter(
    sections: Sequence[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    chapters: dict[str, dict[str, Any]] = {}
    order: list[str] = []
    for section in sections:
        if not isinstance(section, Mapping):
            continue
        chapter_id = str(section.get("chapter_id") or "")
        if not chapter_id:
            continue
        if chapter_id not in chapters:
            chapters[chapter_id] = {
                "chapter_id": chapter_id,
                "source_section_ids": [],
                "heading_path": list(section.get("heading_path") or [])[:1] or [chapter_id],
            }
            order.append(chapter_id)
        section_id = str(
            section.get("source_section_id") or section.get("section_id") or ""
        )
        if section_id:
            chapters[chapter_id]["source_section_ids"].append(section_id)
    return [chapters[key] for key in order]


def _build_chapter_request(
    chapter: Mapping[str, Any],
    metadata_by_section_id: Mapping[str, Mapping[str, Any]],
    *,
    section_hashes: Sequence[str],
    concept_text: str | None,
    prompt_version: str,
    model: str,
    effort: str | None,
    metadata_version: int,
) -> LlmRequest:
    sections_payload: list[dict[str, Any]] = []
    for section_id in chapter["source_section_ids"]:
        entry = metadata_by_section_id.get(section_id, {})
        sections_payload.append(
            {
                "section_id": section_id,
                "heading_path": list(entry.get("heading_path") or []),
                "summary": str(entry.get("summary") or ""),
                "search_keys": list(entry.get("search_keys") or []),
                "identifiers": list(entry.get("identifiers") or [])[:16],
                "related_sections": [
                    {
                        "target_section_id": str(related.get("target_section_id") or ""),
                        "relation_hint": str(related.get("relation_hint") or ""),
                    }
                    for related in (entry.get("related_sections") or [])
                    if isinstance(related, Mapping)
                ][:8],
            }
        )
    prompt_payload = {
        "task": "chapter_anchors",
        "artifact_role": CHAPTER_ANCHORS_ROLE,
        "instructions": (
            "Generate a Chapter Key Anchor that helps an Agent decide whether"
            " to enter this chapter for a task. summary must capture the"
            " chapter's intent in 2-3 sentences (natural language)."
            " key_topics must be 3-6 short natural-language phrases that"
            " describe the chapter's themes (no code symbols / API names)."
            " important_sections must be section_ids drawn from the input,"
            " listing the sections an Agent should read first (max 5)."
            " notes must be 0-3 cautions the Agent should keep in mind when"
            " applying constraints derived from this chapter."
            " Output JSON only."
        ),
        "return_shape": {
            "summary": "string",
            "key_topics": ["string"],
            "important_sections": ["string"],
            "notes": ["string"],
        },
        "chapter": {
            "chapter_id": chapter["chapter_id"],
            "heading_path": list(chapter.get("heading_path") or []),
            "sections": sections_payload,
        },
        "core_concept": concept_text or "",
    }
    prompt = json.dumps(prompt_payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    source_hash = _sha256_text(
        _stable_json(
            {
                "chapter_id": chapter["chapter_id"],
                "section_hashes": sorted(str(value) for value in section_hashes),
            }
        )
    )
    return LlmRequest(
        task="chapter_anchors",
        stage="chapter_key_anchor",
        prompt=prompt,
        prompt_version=prompt_version,
        model=model,
        source_hash=source_hash,
        semantic_hash=source_hash,
        section_id=chapter["chapter_id"],
        metadata_version=metadata_version,
        effort=effort,
        section_hashes={
            section_id: hash_value
            for section_id, hash_value in zip(
                chapter["source_section_ids"], section_hashes, strict=False
            )
        },
        input_hashes={"concept_text": _sha256_text(concept_text or "")},
        context_hashes={
            "artifact_role": _sha256_text(CHAPTER_ANCHORS_ROLE),
            "prompt_version": _sha256_text(prompt_version),
        },
    )


def _anchor_from_llm_output(
    chapter: Mapping[str, Any],
    metadata_by_section_id: Mapping[str, Mapping[str, Any]],
    *,
    llm_output: Mapping[str, Any] | None,
    generated_at: str | None,
) -> dict[str, Any] | None:
    """Translate LLM output into the chapter anchor entry shape.

    Returns the anchor dict if the LLM output is parseable and contains a
    non-empty summary. Returns None when the LLM output is missing or
    unparseable (the caller treats the chapter as failed; no alternate
    fallback anchor is provided).
    """

    section_ids = list(chapter["source_section_ids"])
    _ = metadata_by_section_id
    base_anchor = {
        "chapter_id": chapter["chapter_id"],
        "source_section_ids": section_ids,
        "generated_at": generated_at,
    }
    if not isinstance(llm_output, Mapping):
        return None

    summary = llm_output.get("summary")
    key_topics = llm_output.get("key_topics")
    important_sections = llm_output.get("important_sections")
    notes = llm_output.get("notes")
    if not isinstance(summary, str) or not summary.strip():
        return None
    if not isinstance(key_topics, Sequence) or isinstance(key_topics, (str, bytes)):
        key_topics = []
    if not isinstance(important_sections, Sequence) or isinstance(
        important_sections, (str, bytes)
    ):
        important_sections = []
    if not isinstance(notes, Sequence) or isinstance(notes, (str, bytes)):
        notes = []

    section_id_set = set(section_ids)
    filtered_important = [
        str(value)
        for value in important_sections
        if isinstance(value, str) and value in section_id_set
    ][:5]
    if not filtered_important:
        filtered_important = section_ids[:3]
    anchor = {
        **base_anchor,
        "summary": summary.strip(),
        "key_topics": [str(value).strip() for value in key_topics if str(value).strip()][:6],
        "important_sections": filtered_important,
        "notes": [str(value).strip() for value in notes if str(value).strip()][:3],
    }
    return anchor


def _llm_error_message(result: LlmGenerationResult) -> str:
    diagnostic_items = result.diagnostic_items or []
    for item in reversed(diagnostic_items):
        message = item.get("message") if isinstance(item, Mapping) else None
        if isinstance(message, str) and message.strip():
            return message.strip()
    diagnostics = result.diagnostics or []
    for diagnostic in reversed(diagnostics):
        message = getattr(diagnostic, "message", None)
        if isinstance(message, str) and message.strip():
            return message.strip()
    return ""


def _resolve_provider(
    provider: LlmProvider | None,
    llm_config: Any | None,
) -> LlmProvider:
    if provider is not None:
        return provider
    if _config_value(llm_config, "provider", None) or _config_value(llm_config, "providers", None):
        return build_spec_core_llm_provider(llm_config)
    return FakeLlmProvider()


def _select_llm_config(llm_config: Any | None) -> Any | None:
    if _config_value(llm_config, "providers", None):
        return select_llm_provider_config(llm_config)
    return llm_config


def _model_name(llm_config: Any, provider_id: str) -> str:
    model = _config_value(llm_config, "model", None)
    if isinstance(model, str) and model:
        return model
    return provider_id or "fake"


def _config_value(config: Any, key: str, default: Any) -> Any:
    if config is None:
        return default
    if isinstance(config, Mapping):
        return config.get(key, default)
    return getattr(config, key, default)


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _stable_json(payload: Mapping[str, Any]) -> str:
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


__all__ = [
    "CHAPTER_ANCHORS_PROMPT_VERSION",
    "CHAPTER_ANCHORS_ROLE",
    "ChapterAnchorsCache",
    "ChapterAnchorsGeneration",
    "generate_chapter_anchors",
]
